replicaCount: 2

image:
  repository: 

service:
  type: NodePort
  port: 9000

host:
routePrefix:

postgresql:
  enabled: true
  postgresqlUsername: 
  postgresqlPassword: 
  postgresqlDatabase: 
  service:
    port: 
